### ISSUE TITLE
500 internal server error for PDF having more than 5 pages

### ISSUE THREAD

**Issue by supriyakhankar** [niklasravnsborg/laravel-pdf#121]
I am using laravel 5.2.
I am trying to download PDF having pages more than 5. My array is having around 1K rows. 
Download function gives me 500 internal server error.

I tried below code in my blade file
set_time_limit(0);
ini_set("memory_limit",'1024M');
ini_set('max_execution_time', 0);

Now I am getting 503 Service unavailable error.

**Comment by dheroefic** [comment]
Please see the log attached in storage/logs/laravel${date}.log
I believe it has to do with: 
> The HTML code size is larger than pcre.b                                                                                                             acktrack_limit 1000000. You should use WriteHTML() with smaller string lengths.
Solved by this:
ini_set("memory_limit",'1024M');
ini_set('max_execution_time', 0);
ini_set('pcre.backtrack_limit', (should be >count($html)));

**Comment by legitquest123** [comment]
Hii even i am facing same problem and i used below lines but still not working. Help appreciated.

ini_set('max_execution_time', '300');
ini_set('pcre.backtrack_limit', 10000000000);
Please help

**Comment by dheroefic** [comment]
@legitquest123 can you share the log in `storage/logs/laravel${date}.log`?
